### ISSUE TITLE
Erro ao iniciar o programa sem o arquivo `option_db.txt`

### ISSUE THREAD

**Issue by ppcmiranda** [ppcmiranda/gera-senha#1]
O programa assume que o arquivo de preferências do usuário existe e resulta em erro caso contrário.

Minha sugestão é que o arquivo seja criado apenas caso o usuário altere as configurações padrão e não produza erro se não existir.

A mensagem de erro original :

```
Traceback (most recent call last):
  File "gerasenha.py", line 401, in <module>
    Application().run()
  File "gerasenha.py", line 155, in __init__
    self.build_interface()
  File "gerasenha.py", line 163, in build_interface
    self.root.option_readfile('option_db.txt')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 945, in option_readfile
    self.tk.call('option', 'readfile', fileName, priority)
_tkinter.TclError: couldn't open "option_db.txt": no such file or directory
```

**Comment by omiranda-dev** [comment]
Estou com a versão nova. Como abro um branch para corrigir esse problema?

**Comment by ppcmiranda** [comment]
Só mandar um pull request que eu faço o merge.

**Comment by omiranda-dev** [comment]
Mandei um pull request anteontem, dia 10.

Em qua., 9 de set. de 2020 às 14:41, Pedro Miranda <notifications@github.com>
escreveu:
